URL      = https://github.com/philipc/tinyrl.git
VERSION  = b5471fe6e8aa81355ae5552a8f6254ba092eaec7
METHOD   = git
AUTOCONF = cmake CMakeLists.txt
AUTOCONF += -DCMAKE_INSTALL_PREFIX=/ -DCMAKE_SYSTEM_PREFIX_PATH=$(STAGEDIR)
CONFIGURE = noconfigure

include $(ROOTDIR)/tools/automake.inc
