URL      = https://github.com/lloyd/yajl.git
VERSION  = 2.1.0
METHOD   = git
AUTOCONF = cmake .
AUTOCONF += -DCMAKE_INSTALL_PREFIX=/ -DCMAKE_SYSTEM_PREFIX_PATH=$(STAGEDIR)
CONFIGURE = noconfigure

include $(ROOTDIR)/tools/automake.inc
