URL      = https://github.com/sbyx/odhcp6c.git
METHOD   = git
AUTOCONF = cmake CMakeLists.txt
AUTOCONF += -DCMAKE_INSTALL_PREFIX=/ -DCMAKE_SYSTEM_PREFIX_PATH=$(STAGEDIR)
VERSION = d21764d12bb799f89d42c94dc20d4adb6d588077

include $(ROOTDIR)/tools/automake.inc
