
URL = http://www.python.org/ftp/python/3.4.2/Python-3.4.2.tar.xz

CONFVARS += ac_cv_prog_READELF=$(CROSS_COMPILE)readelf
CONFVARS += ac_cv_buggy_getaddrinfo=no
CONFVARS += ac_cv_file__dev_ptmx=yes
CONFVARS += ac_cv_file__dev_ptc=no
CONFVARS += ac_cv_have_long_long_format=yes

include $(ROOTDIR)/tools/automake.inc


