
URL      = git://nbd.name/uqmi.git
VERSION  = b61b3e8ff2b29e08b53eabc7b813c1c87c734947
METHOD   = git
AUTOCONF = cmake CMakeLists.txt
AUTOCONF += -DCMAKE_INSTALL_PREFIX=/ -DCMAKE_SYSTEM_PREFIX_PATH=$(STAGEDIR)

include $(ROOTDIR)/tools/automake.inc

