
CONFOPTS  = --disable-nls
CONFOPTS += --disable-example
CONFOPTS += --disable-kernel-module
CONFOPTS += --enable-lib
CONFOPTS += --enable-util

MAKEVARS  = LIBS=-lpthread

URL = http://downloads.sourceforge.net/fuse/fuse-2.9.2.tar.gz

include $(ROOTDIR)/tools/automake.inc

